SELECT_ADMIN_DATA = "select-admin"
ADD_ADMIN_DATA = "add-admin"
SUBMIT_ADD_ADMIN_DATA = "submit-add-admin"
REMOVE_ADMIN_DATA = "remove-admin-"
SUBMIT_REMOVE_ADMIN_DATA = "submit-remove-admin-"

SELECT_EDITOR_DATA = "select-editor"
ADD_EDITOR_DATA = "add-editor"
SUBMIT_ADD_EDITOR_DATA = "submit-add-editor"
REMOVE_EDITOR_DATA = "remove-editor-"
SUBMIT_REMOVE_EDITOR_DATA = "submit-remove-editor-"
